import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';
import { useRouter } from 'next/router';

function Home() {
	const { data: session, status } = useSession();
	const router = useRouter();
	const signInHandler = () => {
		if (status === 'authenticated') {
			console.log(session.user.email);
			router.push('/main');
			//signOut()
		} else {
			signIn();
		}
	};
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="max-w-3xl h-full m-auto">
				<div className="flex justify-between p-5 items-center border-b-2">
					<img src="img/rubik_1.png" className="w-12 h-12" />
					<button
						onClick={signInHandler}
						className="bg-green-700 text-yellow-300 hover:bg-yellow-300 hover:text-green-700 p-3 hover:scale-105 transition transform duration-200 easy-out"
					>
						SignUp
					</button>
				</div>
			</div>
		</div>
	);
}
export default Home;
